// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dipdgigmplhphlotxkbm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRpcGRnaWdtcGxocGhsb3R4a2JtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDczMjkyMDIsImV4cCI6MjA2MjkwNTIwMn0.tnuS80JrUFdNWKWYeEuMIux7NzLl0kYY-jBIjGEbCbo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);